additional_skills = [
    "Analysis",
    "Troubleshooting",
    "Security",
    "DevOps",
    "Virtualization",
    "Encryption",
    "Networking",
    "Scalability",
    "Configuration",
    "Middleware",
    "Authentication",
    "Authorization",
    "Cryptography",
    "Design",
    "Modeling",
    "Monitoring",
    "Scripting",
    "Debugging",
    "Performance",
    "Abstraction",
    "Concurrency",
    "Automation",
    "Optimization",
    "Deployment",
    "Frameworks",
    "Libraries",
    "APIs",
    "Patterns",
    "Modularity",
    "Interoperability",
    "Compliance",
    "Architecture",
    "Metrics",
    "User-Centric",
    "Backend",
    "Frontend",
    "Responsive",
    "Full-Stack",
    "RESTful",
    "GraphQL",
    "REST",
    "AJAX",
    "API",
    "JSON",
    "XML",
    "HTML5",
    "CSS3",
    "SASS",
    "WebSockets",
    "DOM",
    "State",
    "Functional",
    "Imperative",
    "Declarative",
    "Inheritance",
    "Polymorphism",
    "Encapsulation",
    "Abstraction",
    "Interface",
    "Composition",
    "Prototype",
    "Class",
    "Object",
    "Method",
    "Algorithm",
    "Heuristic",
    "Data",
    "Structure",
    "Recursion",
    "Iteration",
    "Big-O",
    "Complexity",
    "Graph",
    "Tree",
    "Array",
    "Queue",
    "Stack",
    "Hashing",
    "Searching",
    "Sorting",
    "Memory",
    "Pointer",
    "Multithreading",
    "Parallelism",
    "Synchronization",
    "Deadlock",
    "Semaphore",
    "Kernel",
    "System",
    "Application",
    "Embedded",
    "Database",
    "Query",
    "Indexing",
    "Transactions",
    "Normalization",
    "ACID",
    "NoSQL",
    "File",
    "I/O",
    "Backup",
    "Recovery",
    "Cloud",
    "AWS",
    "Azure",
    "GCP",
    "Lambda",
    "Serverless",
    "Container",
    "Microservices",
    "Middleware",
    "Integration",
    "REST",
    "SOAP",
    "RPC",
    "CORBA",
    "IoT",
    "Wearables",
    "Mobile",
    "Desktop",
    "Hybrid",
    "UI/UX",
    "Wireframe",
    "Prototype",
    "Accessibility",
    "Multithreading",
    "Parallelism",
    "Distributed",
    "Message-Passing",
    "Filesystem",
    "Concurrency",
    "Buffer",
    "Cache",
    "Paging",
    "Segmentation",
    "Virtual",
    "Overloading",
    "Polymorphism",
    "Abstraction",
    "Encapsulation",
    "Cohesion",
    "Coupling",
    "Patterns",
    "MVC",
    "MVVM",
    "Singleton",
    "Observer",
    "Factory",
    "Strategy",
    "Proxy",
    "Command",
    "Interpreter",
    "Adapter",
    "Template",
    "Delegate",
    "Decorator",
    "Visitor",
    "Builder",
    "Iterator",
    "Mediator",
    "Chain-of-Responsibility",
    "State",
    "Facade",
    "Composite",
    "Flyweight",
    "Bridge"
]

common_single_words = [
    "algorithm",
    "problem-solving",
    "coding",
    "object-oriented",
    "oop",
    "version",
    "control",
    "agile",
    "scrum",
    "front-end",
    "back-end",
    "database",
    "mobile",
    "testing",
    "automation",
    "ci/cd",
    "git",
    "linux",
    "cloud",
    "aws",
    "azure",
    "docker",
    "kubernetes",
    "microservices",
    "restful",
    "api",
    "java",
    "python",
    "javascript",
    "html",
    "css",
    "sql",
    "nosql",
    "communication",
    "teamwork",
    "documentation",
    "learning",
    "analytical",
    "interpersonal",
    "innovation",
    "adaptability",
    "multitasking",
    "leadership",
    "project",
    "collaboration",
    "prototyping",
    "deployment",
    "ux/ui",
    "security",
    "methodology",
    "framework",
    "library",
    "optimization",
    "architecture",
    "scalability",
    "efficiency",
    "workflow",
    "integration",
    "refactor",
    "maintenance",
    "versioning",
    "continuous",
    "delivery",
    "functional",
    "paradigm",
    "structure",
    "query",
    "protocol",
    "network",
    "monitoring",
    "java",
    "python",
    "c++",
    "c#",
    "javascript",
    "typescript",
    "php",
    "ruby",
    "swift",
    "kotlin",
    "react",
    "angular",
    "vue",
    "django",
    "spring",
    "laravel",
    "express",
    "node",
    "mongodb",
    "mysql",
    "postgresql",
    "redis",
    "graphql",
    "aws",
    "azure",
    "docker",
    "kubernetes",
    "jenkins",
    "ansible",
    "terraform",
    "git",
    "svn",
    "agile",
    "scrum",
    "kanban",
    "problem-solving",
    "debugging",
    "documentation",
    "testing",
    "automation",
    "ci/cd",
    "ux/ui"
    # ... (add more words as needed)
]

all_skills = common_single_words + additional_skills

filtered_skills = [skill for skill in all_skills if skill in
                   [
    "java", "python", "javascript", "html", "css", "sql", "nosql",
    "c++", "c#", "c", "typescript", "php", "ruby", "swift", "kotlin",
    "react", "angular", "vue", "django", "spring", "laravel",
    "express", "node", "mongodb", "mysql", "postgresql", "redis",
    "graphql", "aws", "azure", "docker", "kubernetes", "jenkins",
    "ansible", "terraform", "git", "svn",
    "go", "rust", "scala", "perl", "r", "julia", "dart", "lua", "haskell",
    "rails", "clojure", "groovy",
    "bash", "powershell",
    "couchbase", "cassandra", "neo4j", "orientdb", "firebase",
    "dynamodb", "sqlite", "mariadb",
    "flask", "ember", "knockout", "symfony", "codeigniter", "aspnet",
    "play", "phoenix", "qt",
    "hadoop", "spark",
    "gcp", "ibmcloud", "digitalocean", "heroku",
    "alibabacloud", "oraclecloud", "vmwarecloud", "openshift",
    "pcf",
    "openshift", "nomad", "mesos", "openstack",
    "circleci", "gitlab", "travisci", "bitbucket",
    "bamboo", "teamcity", "spinnaker",
    "chef", "puppet", "saltstack", "packer",
    "mercurial", "bazaar", "fossil",
    "backbone", "aurelia", "svelte", "polymer",
    "blazor", "gatsby", "nextjs", "nuxt",
    "cobol", "fortran", "lisp", "ada", "prolog", "scheme", "smalltalk",
    "forth", "erlang", "elixir", "racket", "perl6"
]]